/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IMetadataModule,
  IMetadataModuleInterface,
} from "../IMetadataModule";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "tokenURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IMetadataModule__factory {
  static readonly abi = _abi;
  static createInterface(): IMetadataModuleInterface {
    return new utils.Interface(_abi) as IMetadataModuleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMetadataModule {
    return new Contract(address, _abi, signerOrProvider) as IMetadataModule;
  }
}
