name: Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Forge tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-63ed1099a74fded7c3a7182b5a508bd7d16743d3

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -v --gas-report
        id: test
