name: Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Forge tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Setup Node v16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'pnpm'
      - name: Add NPM_TOKEN
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install dependencies
        run: pnpm install
      - name: Compile contracts
        run: |
          pnpm compile
        id: compile
      - name: Run Forge tests
        run: |
          forge test -vvv --gas-report
        id: test
      - name: Code coverage
        run: |
          forge coverage --report lcov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: lcov.info