name: Danger Bot
on:
  pull_request:
    types:
      # Defaults https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
      - 'opened'
      - 'synchronize'
      - 'reopened'
      # Custom - whenever labels are changed
      - 'labeled'
      - 'unlabeled'

jobs:
  danger:
    runs-on: ubuntu-latest
    name: Danger JS
    # TODO: remove this line when ready to start publishing
    if: ${{ false }} 
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
      - name: Setup Node v16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'pnpm'

      - name: Run Danger JS
        env:
          # See https://github.com/danger/danger-js/issues/1042
          DANGER_GITHUB_API_BASE_URL: 'https://api.github.com'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm dlx danger ci