name: Slither Analysis

on:
    push:
        branches: [master]
    pull_request:

jobs:
    static-analysis:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Install Foundry
              uses: onbjerg/foundry-toolchain@v1
              with:
                  version: nightly

            - name: Install dependencies
              run: forge install

            - name: Run Slither
              env:
                  TERM: xterm-color
              uses: crytic/slither-action@main
              continue-on-error: true
              id: slither
              with:
                  slither-config: "slither.config.json"
                  solc-version: 0.8.16
                  sarif: results.sarif

            # Below call currently raises Error: Advanced Security must be enabled for this repository to use code scanning.
            # https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/setting-up-code-scanning-for-a-repository
            # - name: Upload SARIF file for margin
            #   uses: github/codeql-action/upload-sarif@v2
            #   id: upload-1
            #   with:
            #     sarif_file: ${{ steps.slither.outputs.sarif }}
